server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://db:3306/user_management?createDatabaseIfNotExist=true
    username: user
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql:
    database: mysql


jwt:
  secret-key: 'E/P`ADNG(C6_$V#ciH6CUtw=we&%y[Dq9s6S}Vx^R;f?)1@>Nr%>W_1wc~kWRPk'


