server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://db:3306/user_management?createDatabaseIfNotExist=true
    username: user
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sq l: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql:
#  mvc:
#    throw-exception-if-no-handler-found: true
jwt:
  secret-key: 'R9#?7M2?aO1&[+(^qd,;8;BYyWFq5;V~f+G(eF~*s[DID[R1agRiU"tMOuVzo_imZq4t7w9z$C&F)J@NcRfUjXn2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v9y$B&E)H@M'
