server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_management?createDatabaseIfNotExist=true
    username: user
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql:
    database: mysql
    database-platform: org.org.hibernate.dialect.MySQL5InnoDBDialect
